#!/usr/bin/env python3
"""
Generate LaTeX card definitions from a JSON file where
each top-level key is a category containing a list of cards.

Output format:
\\card{category}{name}{subtype}{description}
"""

import json
from pathlib import Path


# ---------- CONFIGURATION ----------

INPUT_JSON = Path("cards.json")
OUTPUT_TEX = Path("cards_generated.tex")

# Warn (but do not fail) if descriptions get very long
DESC_LENGTH_WARNING = 450


# ---------- LATEX ESCAPING ----------
def normalize_unicode(s: str) -> str:
    """
    Convert smart quotes and fancy apostrophes to plain ASCII equivalents.
    """
    replacements = {
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "–": "-",  # en dash
        "—": "--", # em dash
        # add more if needed
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s

def tex_escape(s: str) -> str:
    """
    Escape characters with special meaning in LaTeX.
    Explicit and conservative by design.
    """
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }

    s = normalize_unicode(s)

    for char, escaped in replacements.items():
        s = s.replace(char, escaped)

    return s


# ---------- CARD EMISSION ----------

def emit_front(category: str, card: dict) -> str:
    """
    Convert a single card into a LaTeX \\card command.

    Required card keys:
    - name
    - subtype
    - desc
    """
    name = tex_escape(card["name"])
    subtype = tex_escape(card["subtype"])
    desc = tex_escape(card["desc"])
    category = tex_escape(category)

    return f"\\cardfront{{{name}}}{{{subtype}}}{{{desc}}}"

def emit_back(category: str, card: dict) -> str:
    """
    Convert a single card into a LaTeX \\card command.

    Required card keys:
    - name
    - subtype
    - desc
    """
    name = tex_escape(card["name"])
    subtype = tex_escape(card["subtype"])
    desc = tex_escape(card["desc"])
    category = tex_escape(category)

    return f"\\cardback{{{category}}}"

# ---------- MAIN ----------

def main() -> None:
    if not INPUT_JSON.exists():
        raise FileNotFoundError(f"Missing input file: {INPUT_JSON}")

    data = json.loads(INPUT_JSON.read_text(encoding="utf-8"))

    if not isinstance(data, dict):
        raise TypeError("Top-level JSON must be an object")

    output_lines = []
    warnings = []
    total_cards = 0

    for category, cards in data.items():
        if not isinstance(cards, list):
            raise TypeError(
                f"Category '{category}' must contain a list of cards"
            )

        for idx, card in enumerate(cards, start=1):
            for key in ("name", "subtype", "desc"):
                if key not in card:
                    raise KeyError(
                        f"Card {idx} in category '{category}' "
                        f"missing required key: {key}"
                    )

            if len(card["desc"]) > DESC_LENGTH_WARNING:
                warnings.append(
                    f"[{category}] long desc ({len(card['desc'])} chars): {card['name']}"
                )

            output_lines.append(emit_back(category, card))
            output_lines.append(emit_front(category, card))
            
            total_cards += 1

    OUTPUT_TEX.write_text(
        "% AUTO-GENERATED FILE — DO NOT EDIT\n"
        "% Generated by generate_cards_tex.py\n\n"
        + "\n".join(output_lines)
        + "\n",
        encoding="utf-8",
    )

    if warnings:
        print("Warnings:")
        for w in warnings:
            print(f"  - {w}")

    print(f"Wrote {total_cards} cards to {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
