CREATE TABLE IF NOT EXISTS `gawm`.`games` ( 
`uid` int NOT NULL AUTO_INCREMENT, 
`time` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
`data` JSON NOT NULL , 
UNIQUE `GameUIDIndex` (`uid`)) 
ENGINE = InnoDB;